language: ruby

rvm:
  - 2.1.0

addons:
  postgresql: "9.3"

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake --trace db:migrate test

before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-es
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3
